<a href="https://colab.research.google.com/github/annine1/NLP_Language_Naive_Bayes-and-Logistic_Regression/blob/main/Annine_Duclaire_Kenne_intro_to_wordvectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


<h1 style="font-family:verdana;font-size:300%;text-align:center;background-color:#f2f2f2;color:#0d0d0d">AMMI NLP - Review sessions</h1>

<h1 style="font-family:verdana;font-size:180%;text-align:Center;color:#993333"> Lab 2: Introduction to wordvectors </h1>

**Big thanks to Amr Khalifa who improved this lab and made it to a Jupyter Notebook!**

In [1]:
import io, sys
import numpy as np

In [2]:
def load_vectors(filename):
    fin = io.open(filename, 'r', encoding='utf-8', newline='\n')
    n, d = map(int, fin.readline().split())
    data = {}
    for line in fin:
        tokens = line.rstrip().split(' ')
        data[tokens[0]] = np.asarray([float(x) for x in tokens[1:]])
    return data

In [3]:
# Loading word vectors

print('')
print(' ** Word vectors ** ')
print('')

'''
word_vectors is a dictionary that maps words to their numerical word vector
[word (string)] = [np-array] 
'''
word_vectors = load_vectors('/content/drive/MyDrive/NLP/Week1/Session2/wiki.en.vec')

tree_vector = word_vectors['tree']
print(type(tree_vector), len(tree_vector))



 ** Word vectors ** 

<class 'numpy.ndarray'> 300


In [4]:
print(word_vectors['tree'])

[-0.39784    0.054416   0.21823    0.39507    0.092681  -0.023061
  0.37008   -0.64496    0.3227    -0.032656   0.36157   -0.09288
  0.061203   0.22114    0.051044  -0.17904    0.24627    0.27385
  0.22722    0.406     -0.014682   0.10351   -0.51104    0.019572
 -0.057841  -0.16893    0.096886  -0.18702   -0.12943   -0.6119
 -0.27579    0.36402    0.20499    0.099865   0.080926  -0.013058
  0.24712    0.27284   -0.022597   0.16511    0.12329    0.0063245
 -0.30938   -0.2052     0.075066   0.55976   -0.046072  -0.24232
  0.076304  -0.19305   -0.046893   0.17447   -0.29613   -0.0091035
  0.45577    0.62522   -0.21809   -0.079472   0.35758    0.52445
 -0.063457  -0.45847    0.1742    -0.11709    0.029591  -0.16949
  0.27293   -0.056522   0.012239   0.473     -0.088194  -0.047084
  0.30997   -0.46366    0.044899   0.017134   0.43833    0.1972
 -0.15461   -0.086679  -0.1268    -0.047868  -0.086764  -0.13257
 -0.10754    0.041026   0.14707    0.2428     0.017882   0.31355
  0.26011   -0.1416

The cosinus similarity is given by the following equation:
$cos(u,v) = \frac{u.v}{||u||.||v||} = \frac{\sum_{i}^{n}u_i
*v_i}{\sqrt{{\sum_{i}^{n}u_i^2}}*\sqrt{{\sum_{i}^{n}v_i^2}}}$

- **cos(u,v) = 1**  when u and v lie on the same line and have the same direction.
- **cos(u,v) = -1** when they have exactly opposite directions.
- **cos(u,v) = 0** when the vectors are orthogonal (perpendicular) to each other.

In [5]:
## This function computes the cosine similarity between vectors u and v

def cosine(u, v):
    '''
    Parameters:
    u : 1-D numpy array
    v : 1-D numpy array 
    
    Returns:
    cos (float) : value of the cosine similairy between vectors u, v 
    '''

    ## FILL CODE
    # print(type(u), type(v))

    a = np.dot(u, v)
    eucl_norm_u = np.linalg.norm(u)
    eucl_norm_v = np.linalg.norm(v)
    b = eucl_norm_u * eucl_norm_v
    cos = a / b
    
    return cos 


In [6]:
# compute similarity between words

print('similarity(apple, apples) = %.3f' %
      cosine(word_vectors['apple'], word_vectors['apples']))
print('similarity(apple, banana) = %.3f' %
      cosine(word_vectors['apple'], word_vectors['banana']))
print('similarity(apple, tiger) = %.3f' %
      cosine(word_vectors['apple'], word_vectors['tiger']))

similarity(apple, apples) = 0.637
similarity(apple, banana) = 0.431
similarity(apple, tiger) = 0.212


In [7]:
## Functions for nearest neighbor
## This function returns the word corresponding to 
## nearest neighbor vector of x
## The list exclude_words can be used to exclude some
## words from the nearest neighbors search

def nearest_neighbor(x, word_vectors, exclude_words=[]):
    '''
    Parameters:
    x (string): word to find its nearest neighbour 
    word_vectors (Python dict): {word (string): np-array of word vector}
    exclude_words (list of strings): words to be excluded from the search
    
    Returns:
    best_word (string) : the word whose word vector is the nearest neighbour 
    to the word vector of x
    '''
    best_score = -1.0
    best_word = None
    score = 0.0

    ## FILL CODE
    similarity_list = []
    exclude_words = []
    #  for each vector in word_vec
    for vec in word_vectors:      
      if vec=='cat':
        exclude_words.append(vec)
      elif vec=='cats':
        exclude_words.append(vec)
      
      else:

        cos_similarity = cosine(x, word_vectors[vec])

        similarity_list.append(cos_similarity)

        # sort the similarity list and get the indices of the sorted list
        idx_sorted_similarity = np.argsort(similarity_list)

        # indices of the last most similate vec in word_vectors
        idx_most_sim_vec = idx_sorted_similarity[-1:]
        # print(idx_most_sim_vec)
        neighbors = similarity_list[idx_most_sim_vec[0]]

        score = neighbors
        if score > best_score:
          best_score = score
          best_word = vec

      


            
    return best_word

In [8]:
print('')
print('The nearest neighbor of cat is: ' +
      nearest_neighbor(word_vectors['cat'], word_vectors, exclude_words = ['cat', 'cats']))


The nearest neighbor of cat is: dog


In [9]:
l =np.array([3,0,1])
l_=np.argsort(l)
print(l_)
idx=l_[:]
print(idx)
print(l[idx])

[1 2 0]
[1 2 0]
[0 1 3]


#### Hint (using python priorty queues with the heapq datastructure): 
if you don't want to store all the words and scores you can use the priortiy queue and only store the best K element so far. 

**Knn Goal**:
- The **k-Nearest** neighbors algorithm is a method which takes a vector as input and finds the other vectors in the dataset that are closest to it.
- The 'k' is the number of "nearest neighbors" to find (e.g. k=2 finds the closest two neighbors).

In [10]:

## This function return the words corresponding to the
## K nearest neighbors of vector x.
## You can use the functions heappush and heappop.

def knn(x, vectors, k):
    '''
    Parameters:
    x (string): word to find its nearest neighbour 
    word_vectors (Python dict): {word (string): np-array of word vector}
    k (int): number of nearest neighbours to be found
    
    Returns: 
    k_nearest_neighbors (list of tuples): [(score, word), (score, word), ....]
    '''

    similarity_list = []
    words = []
    exclude_words = []
    ## FILL CODE
    #  for each vector in word_vec
    for vec in vectors:
      if vec=='cat':
        exclude_words.append(vec)
      elif vec=='cats':
        exclude_words.append(vec)
      
      else:
        cos_similarity = cosine(x, vectors[vec])
        # print(cos_similarity)
        similarity_list.append(cos_similarity)
        words.append(vec)

        # sort the similarity list and get the indices of the sorted list
        idx_sorted_similarity = np.argsort(similarity_list)

        # indices of the k most similate vec in word_vectors
        idx_k_most_sim_vec = idx_sorted_similarity[-k:]


    # list of k-nearest neighbors
    k_nearest_neighbors = []
    for i in idx_k_most_sim_vec:
       k_nearest_neighbors.append((similarity_list[i], words[i]))
    return k_nearest_neighbors

In [11]:
knn_cat = knn(word_vectors['cat'], word_vectors, 5)
knn_cat

[(0.458395310030411, 'pig'),
 (0.5381171978114956, 'dogs'),
 (0.548941402928511, 'rabbit'),
 (0.5725849995167527, 'pet'),
 (0.6380517245741391, 'dog')]

In [12]:
knn_cat = knn(word_vectors['cat'], word_vectors, 5)
print('')
print('cat')
print('--------------')
for score, word in knn(word_vectors['cat'], word_vectors, 5):
    print (word + '\t%.3f' % score)



cat
--------------
pig	0.458
dogs	0.538
rabbit	0.549
pet	0.573
dog	0.638


#### Hint: 
To find the analogies, we find the nearest neighbour associated with the wordvector d
$$ d = \frac{c}{\Vert {c} \Vert} + \frac{b}{\Vert {b} \Vert} - \frac{a}{\Vert {a} \Vert}$$


In [13]:
## This function return the words d, such that a:b and c:d
## verifies the same relation

def analogy(a, b, c, word_vectors):
    '''
    Parameters:
    a (string): word a
    b (string): word b
    c (string): word c
    word_vectors (Python dict): {word (string): np-array of word vector}
    
    Returnrs: 
    the word d (string) associated with c such that c:d is similar to a:b 
    
    '''
    
    ## FILL CODE
    term1 = word_vectors[c] / (np.linalg.norm(word_vectors[c]))
    term2 = word_vectors[b] / (np.linalg.norm(word_vectors[b]))
    term3 = word_vectors[a] / (np.linalg.norm(word_vectors[a]))
    d1 = term1 + term2 - term3
    d = knn(d1, word_vectors, k=1)
    print(d)


    return d[0][1]

In [14]:
# Word analogies

print('')
print('france - paris + rome = ' + analogy('paris', 'france', 'rome', word_vectors))


[(0.7664637139191509, 'italy')]
france - paris + rome = italy


## A word about biases in word vectors

In [15]:
## A word about biases in word vectors:

print('')
print('similarity(genius, man) = %.3f' %
      cosine(word_vectors['man'], word_vectors['genius']))
print('similarity(genius, woman) = %.3f' %
      cosine(word_vectors['woman'], word_vectors['genius']))


similarity(genius, man) = 0.445
similarity(genius, woman) = 0.325


In [16]:
## Compute the association strength between:
##   - a word w
##   - two sets of attributes A and B

def association_strength(w, A, B, vectors):
    '''
    Parameters:
    w (string): word w
    A (list of strings): The words belonging to set A
    B (list of strings): The words belonging to set B
    vectors (Python dict): {word (string): np-array of word vector}
    
    Returnrs: 
    strength (float): the value of the association strength 
    '''
    
    strength = 0.0
    # part_a = 0.0
    # part_b = 0.0 
    sum_A = 0.0
    sum_B = 0.0
    
    ## FILL CODE
    for i in A:
      sum_A += (1/len(A))*cosine(vectors[w], vectors[i])
    
    for j in B:
      sum_B += (1/len(B))*cosine(vectors[w], vectors[j])
     
    strength = sum_A - sum_B


    return strength

In [17]:
## Perform the word embedding association test between:
##   - two sets of words X and Y
##   - two sets of attributes A and B

def weat(X, Y, A, B, vectors):
    '''
    Parameters:
    X (list of strings): The words belonging to set X
    Y (list of strings): The words belonging to set Y
    A (list of strings): The words belonging to set A
    B (list of strings): The words belonging to set B
    vectors (Python dict): {word (string): np-array of word vector}
    
    Returns: 
    score (float): the value of the group association strength  
    '''
    
    score = 0.0
    sum_X = 0.0
    sum_Y = 0.0
    
    ## FILL CODE
    for i in X:
      sum_X += association_strength(i, A, B, vectors)
    for j in Y:
      sum_Y += association_strength(j, A, B, vectors)
      
    score = sum_X - sum_Y  

    return score

In [18]:
## Replicate one of the experiments from:
##
## Semantics derived automatically from language corpora contain human-like biases
## Caliskan, Bryson, Narayanan (2017)

career = ['executive', 'management', 'professional', 'corporation', 
          'salary', 'office', 'business', 'career']
family = ['home', 'parents', 'children', 'family',
          'cousins', 'marriage', 'wedding', 'relatives']
male = ['john', 'paul', 'mike', 'kevin', 'steve', 'greg', 'jeff', 'bill']
female = ['amy', 'joan', 'lisa', 'sarah', 'diana', 'kate', 'ann', 'donna']

print('')
print('Word embedding association test: %.3f' %
      weat(career, family, male, female, word_vectors))


Word embedding association test: 0.847


## Word translation using word vectors

In the following, we will use word vectors in English and French to translate words from English to French. The idea is to learn a linear function that maps English word vectors to their correponding French word vectors. To learn this linear mapping, we will use a small bilingual lexicon, that contains pairs of words in English and French that are translations of each other.

The following function will load the small English-French bilingual lexicon:

In [19]:
def load_lexicon(filename):
    '''
    Parameters:
    filename(string): the path of the lexicon
    
    Returns:
    data(list of pairs of string): the bilingual lexicon
    '''
    fin = io.open(filename, 'r', encoding='utf-8', newline='\n')
    data = []
    for line in fin:
        a, b = line.rstrip().split(' ')
        data.append((a, b))
    return data

In [20]:
word_vectors_en = load_vectors('/content/drive/MyDrive/NLP/Week1/Session2/wiki.en.vec')
word_vectors_fr = load_vectors('/content/drive/MyDrive/NLP/Week1/Session2/wiki.fr.vec')
lexicon = load_lexicon("/content/drive/MyDrive/NLP/Week1/Session2/lexicon-en-fr.txt")
print(lexicon[:5])

[('the', 'le'), ('the', 'les'), ('the', 'la'), ('and', 'et'), ('was', 'fut')]


In [21]:
# We split the lexicon into a train and validation set
train = lexicon[:5000]
valid = lexicon[5000:5100]

The following function will learn the mapping from English to French. The idea is to build two matrices $X_{\text{en}}$ and $X_{\text{fr}}$, and to find a mapping $M$ that minimizes $||X_{\text{en}} W - X_{\text{fr}} ||_2$. In numpy, this mapping can be obtained by using the `numpy.linalg.lstsq` function.

In [22]:
def align(word_vectors_en, word_vectors_fr, lexicon):
    '''
    Parameters:
    word_vectors_en(dict: string -> np.array): English word vectors
    word_vectors_en(dict: string -> np.array): French word vectors
    lexicon(list of pairs of string): bilingual training lexicon
    
    Returns
    mapping(np.array): the mapping from English to French vectors
    '''
    x_en, x_fr = [], []
    
    ## FILL CODE
    for en_word, fr_word in lexicon:
      en_vec = word_vectors_en[en_word]
      fr_vec = word_vectors_fr[fr_word]

      #append
      x_en.append(en_vec)
      x_fr.append(fr_vec)

    # X = np.vstack(x_en)
    # Y = np.vstack(x_fr)
    M = np.linalg.lstsq(x_en, x_fr)  

    
    return M[0]

In [23]:
mapping = align(word_vectors_en, word_vectors_fr, lexicon)
mapping

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:24: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.


array([[-0.06183285, -0.01071552,  0.00175985, ..., -0.01107046,
         0.01629405, -0.01644996],
       [-0.01655313, -0.02930488,  0.09810107, ..., -0.01744702,
        -0.02848298,  0.02070179],
       [-0.01970861, -0.0147154 ,  0.01231819, ...,  0.03036093,
        -0.00209909, -0.00944313],
       ...,
       [ 0.0669847 ,  0.02351181,  0.02041902, ...,  0.00886501,
         0.08635366,  0.00595836],
       [ 0.01936122,  0.00552446,  0.01234669, ..., -0.00623332,
        -0.05116348,  0.05634361],
       [ 0.00530333, -0.03424679, -0.03369923, ..., -0.01344391,
        -0.00051053, -0.00491391]])

Given a mapping, a set of word English word vector and French word vectors, the next function will translate the English word to French. To do so, we apply the mapping on the English word, and retrieve the nearest neighbor of the obtained vector in the set of French word vectors. The translation is then the corresponding French word.

In [24]:
def translate(word, word_vectors_en, word_vectors_fr, mapping):
    '''
    Parameters:
    word(string): an English word
    word_vectors_en(dict: string -> np.array): English word vectors
    word_vectors_en(dict: string -> np.array): French word vectors
    mapping(np.array): the mapping from English to French vectors
    
    Returns
    A string containing the translation of the English word
    '''
    
    ## FILL CODE
    eng_word = word_vectors_en[word]
    pred = eng_word @ mapping
    pred_NearestN_fr = knn(pred, word_vectors_fr, k=1)

     

    return pred_NearestN_fr[0][1]

In [28]:
print(translate("world", word_vectors_en, word_vectors_fr, mapping))
print(translate("machine", word_vectors_en, word_vectors_fr, mapping))
print(translate("learning", word_vectors_en, word_vectors_fr, mapping))

monde
machine
apprentissage


Finally, let's implement a function to evaluate this method on the validation lexicon:

In [33]:
def evaluate(valid, word_vectors_en, word_vectors_fr, mapping):
    '''
    Parameters:
    valid(a list of pairs of string): the validation lexicon
    word_vectors_en(dict: string -> np.array): English word vectors
    word_vectors_en(dict: string -> np.array): French word vectors
    mapping(np.array): the mapping from English to French vectors
    
    Returns
    Accuracy(float): the accuracy on the validation lexicon
    '''
    acc, n = 0.0, 0
    
    ## FILL CODE
    for en_word, fr_word in valid:
      eng_fr = translate(en_word, word_vectors_en, word_vectors_fr, mapping)
      if eng_fr == fr_word:
        acc += 1 
      n +=1
      
    return (acc/n)*100

In [34]:
evaluate(valid, word_vectors_en, word_vectors_fr, mapping)

64.0